### ISSUE TITLE
This is a fatal error occured in decoding big image

### ISSUE THREAD

**Issue by carbon-lab** [image-js/tiff#25]
Error message:
`
Uncaught TypeError: Cannot read property 'length' of undefined
    at TIFFDecoder.readStripData (.../node_modules/tiff/lib/tiffDecoder.js:180:42)
    at TIFFDecoder.decodeImageData (.../node_modules/tiff/lib/tiffDecoder.js:151:22)
    at TIFFDecoder.decodeIFD (.../node_modules/tiff/lib/tiffDecoder.js:100:18)
    at TIFFDecoder.decode (.../node_modules/tiff/lib/tiffDecoder.js:54:30)
    at Object.decodeTIFF [as decode] (.../node_modules/tiff/lib/index.js:10:20)
`
This error appeared when I decode a very big image (21600 x 21600 px).

**Comment by carbon-lab** [comment]
**The error message is:**
Uncaught TypeError: Cannot read property 'length' of undefined
    at TIFFDecoder.readStripData (/root/Pictures/work/node_modules/tiff/lib/tiffDecoder.js:180:42)
    at TIFFDecoder.decodeImageData (/root/Pictures/work/node_modules/tiff/lib/tiffDecoder.js:151:22)
    at TIFFDecoder.decodeIFD (/root/Pictures/work/node_modules/tiff/lib/tiffDecoder.js:100:18)
    at TIFFDecoder.decode (/root/Pictures/work/node_modules/tiff/lib/tiffDecoder.js:54:30)
    at Object.decodeTIFF [as decode] (/root/Pictures/work/node_modules/tiff/lib/index.js:10:20)

**Comment by targos** [comment]
Please provide us an image that triggers this error and we'll look into it.

**Comment by carbon-lab** [comment]
I am so sorry about that. The image is not public at first and its size is 300MB+ so how to send it?

**Comment by targos** [comment]
I'm asking because I tried with a 25000 x 25000 px image created with Photoshop (RGB with a color gradient, compressed with LZW). The image is >300MB and did not generate an error

**Comment by carbon-lab** [comment]
Yes, you're right. I also test it by a image created by photoshop (8-bit grey color, uncompressed) and did not generate an error. May be that image file is not standard. But I can use python to open it...

**Comment by targos** [comment]
If you cannot share it privately with me (my email address is public on my profile if you can send me a link), I can only suggest to try and debug on your side to understand why it errors.

**Comment by carbon-lab** [comment]
That's a good idea! Now I have locate the error at `tiff/lib/tiffDecoder.js:180:42`. The `stripOffsets.length` is not defined. What is `stripOffsets`?

**Comment by carbon-lab** [comment]
Ok, I give you the image. What should I do? Put it into a web drive and share it with you?

**Comment by targos** [comment]
Thank you. We found why this image doesn't work. It's because the data is stored as tiles instead of strips. I found a small public image that can be used as a test case and will work on it. I cannot guarantee when that will happen though.

**Comment by carbon-lab** [comment]
You're welcome! I am very fortunate to be able to help you. If there is any need for further help from me, please contact me.  It is very meaningful to develop a convenient graphics library for node.js.
