### ISSUE TITLE
'offset is out of bounds' error when I use the tiff.js demo to open a .tif picture of 164MB 

### ISSUE THREAD

**Issue by huangxc0930** [image-js/tiff#42]
--For some reason, the picture cannot be offered...

RangeError: offset is out of bounds
    at Uint8Array.set (<anonymous>)
    at Object.mmap (tiff.min.js:950)
    at Object.mmap (tiff.min.js:999)
    at ___syscall192 (tiff.min.js:1065)
    at Li (tiff.min.js:1575)
    at Array.Aa (tiff.min.js:1981)
    at rd (tiff.min.js:1146)
    at _TIFFOpen (tiff.min.js:3166)
    at Object.Yh [as ccall] (tiff.min.js:112)
    at new Lb (tiff.min.js:3183)
tiff.min.js:105 RangeError: offset is out of bounds
    at Uint8Array.set (<anonymous>)
    at Object.mmap (tiff.min.js:950)
    at Object.mmap (tiff.min.js:999)
    at ___syscall192 (tiff.min.js:1065)
    at Li (tiff.min.js:1575)
    at Array.Aa (tiff.min.js:1981)
    at rd (tiff.min.js:1146)
    at _TIFFOpen (tiff.min.js:3166)
    at Object.Yh [as ccall] (tiff.min.js:112)
    at new Lb (tiff.min.js:3183)
tiff.min.js:102 Uncaught abort({}) at Error
    at wf (http://seikichi.github.io/tiff.js/tiff.min.js:89:367)
    at Vc (http://seikichi.github.io/tiff.js/tiff.min.js:101:412)
    at ___syscall192 (http://seikichi.github.io/tiff.js/tiff.min.js:1066:155)
    at Li (http://seikichi.github.io/tiff.js/tiff.min.js:1575:41)
    at Array.Aa (http://seikichi.github.io/tiff.js/tiff.min.js:1981:431)
    at rd (http://seikichi.github.io/tiff.js/tiff.min.js:1146:252)
    at _TIFFOpen (http://seikichi.github.io/tiff.js/tiff.min.js:3166:490)
    at Object.Yh [as ccall] (http://seikichi.github.io/tiff.js/tiff.min.js:112:19)
    at new Lb (http://seikichi.github.io/tiff.js/tiff.min.js:3183:87)
    at FileReader.<anonymous> (http://seikichi.github.io/tiff.js/upload.html:47:20)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.

**Comment by targos** [comment]
This repository is not the one of `tiff.js`. It's another project.
